
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Aug 26 20:23:06 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 34;
  public static final int CONST = 22;
  public static final int GREATEQUAL = 44;
  public static final int EQUALS = 8;
  public static final int GREAT = 43;
  public static final int CASE = 25;
  public static final int NOTEQUAL = 42;
  public static final int REM = 26;
  public static final int CONTINUE = 50;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int LESS = 45;
  public static final int MINUS = 20;
  public static final int RPAREN = 7;
  public static final int AND = 40;
  public static final int LESSEQUAL = 46;
  public static final int OR = 39;
  public static final int COMMA = 11;
  public static final int CLASS = 31;
  public static final int INC = 28;
  public static final int DIV = 18;
  public static final int PLUS = 10;
  public static final int IF = 37;
  public static final int DOT = 17;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int EQUAL = 41;
  public static final int NEW = 16;
  public static final int error = 1;
  public static final int MUL = 24;
  public static final int BREAK = 49;
  public static final int IDENT = 36;
  public static final int VOID = 13;
  public static final int SWITCH = 19;
  public static final int LBRACK = 30;
  public static final int COLON = 14;
  public static final int ELSE = 38;
  public static final int LBRACE = 3;
  public static final int QUOT = 51;
  public static final int ENUM = 23;
  public static final int READ = 27;
  public static final int RBRACK = 21;
  public static final int GOTO = 54;
  public static final int WHILE = 48;
  public static final int QUEST = 29;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 15;
  public static final int PROG = 2;
  public static final int BOOL_CONST = 35;
  public static final int DEC = 32;
  public static final int SWAP = 53;
  public static final int MAX = 52;
  public static final int DO = 47;
  public static final int PRINT = 12;
  public static final int NUMBER_CONST = 33;
}

